// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjkogD9R49REqpJl4fAfT2TH2SEiXxxS0',
    appId: '1:1000777785104:android:d1fa0f433c85172dc50f95',
    messagingSenderId: '1000777785104',
    projectId: 'market-c6e1c',
    storageBucket: 'market-c6e1c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBTWk3o3rwDNnRyb_V3jUBxF17_8m8RNGs',
    appId: '1:1000777785104:ios:6fd50a7e0f00c87dc50f95',
    messagingSenderId: '1000777785104',
    projectId: 'market-c6e1c',
    storageBucket: 'market-c6e1c.appspot.com',
    androidClientId: '1000777785104-60cpvefr4va9n7qquuglrd1jse416u49.apps.googleusercontent.com',
    iosClientId: '1000777785104-jd0pfbc23jlf8vm7rv88te4lqppbukc8.apps.googleusercontent.com',
    iosBundleId: 'com.example.myOrgProjects',
  );
}
